Update WASAPI to use projectm_pcm_add_float
projectM-visualizer/projectm pull request #626
Opened 2022-06-10 21:12 UTC by sean5446

`projectm_pcm_add_float_1ch_data` -> `projectm_pcm_add_float`

Tested with STEREO and MONO, both seemed to work. Not sure what the `1ch` was referring to.

2022-06-10 21:41 UTC, revmischa commented
Cool! I think this file needs to be updated: https://github.com/projectM-visualizer/frontend-sdl2/blob/master/src/AudioCaptureImpl_WASAPI.cpp

2022-06-20 17:11 UTC, kblaschke commented
> Cool! I think this file needs to be updated: https://github.com/projectM-visualizer/frontend-sdl2/blob/master/src/AudioCaptureImpl_WASAPI.cpp For the SDL2 application

The WASAPI implementation doesn't even exist in the new SDL2 app's master yet. The WASAPI code in libprojectM's example app here is mostly a copy of the win32 SDK loopback capture sample code, and doesn't care for a lot of stuff like vanishing audio devices (e.g. unplug a headset which was the default device, and see projectM crash).

I'm [currently working on getting the new implementation running](https://github.com/kblaschke/frontend-sdl2/blob/e49cf796ee0977a03439243436ad9107f6e5fd85/src/AudioCaptureImpl_WASAPI.cpp) with proper device selection, which will of course use the latest libprojectM API calls to add audio samples.

2022-06-23 09:27 UTC, kblaschke requested changes

2022-06-24 20:32 UTC, sean5446 commented on src/sdl-test-ui/loopback.cpp
> +            projectm_pcm_add_float(app->projectM(), (float *)pData, nNumFramesToRead, PROJECTM_STEREO);
Thanks for the tip- I'm not good with C++. But trying to learn more! 

Amend the commit? Maybe I did that wrong. I pushed another commit. I was assuming all these commits would just get squashed at merge.

2022-06-24 20:34 UTC, revmischa commented on src/sdl-test-ui/loopback.cpp
> +            projectm_pcm_add_float(app->projectM(), (float *)pData, nNumFramesToRead, PROJECTM_STEREO);
They can certainly be squashed when merged 😄

2022-06-27 17:02 UTC, kblaschke approved these changes

2022-06-27 17:02 UTC, kblaschke commented
Nice, thanks! Will merge as soon as the build tests ran.

2022-06-27 17:09 UTC, merged