Add vcpkg.json
projectM-visualizer/projectm pull request #739
Opened 2023-11-01 09:32 UTC by insel-maz

Use vcpkg in (the recommended) `manifest mode`.

This allows the library to be build by running the following commands in the `Developer PowerShell for VS 2022`:

```PowerShell
cd projectm
cmake . -B build -DCMAKE_BUILD_TYPE=Release "-DCMAKE_INSTALL_PREFIX=$PWD/dist" "-DCMAKE_TOOLCHAIN_FILE=$Env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
cmake --build build --target install --config Release
```

2023-11-04 17:18 UTC, kblaschke commented
Good thing to have!
Yould you mind changing the GitHub Actions Windows workflow accordingly? I think we can then omit the "install dependencies" phase, right?

2023-11-04 17:20 UTC, kblaschke requested changes
The GitHub Actions workflow for the Windows builds need to be stripped of the "install dependencies" pahse, as this is not required in manifest mode.

Would also be nice if you'd update the build instructions for Windows accordingly.

2023-11-16 13:59 UTC, Blaquewithaq commented
I'll finish this PR off sometime today

2023-11-16 18:49 UTC, kblaschke commented
Done in PR #744, so closing this one. Still thanks for the great idea!

2023-11-16 18:49 UTC, closed without merging