Refactor waveform aligner and add test
projectM-visualizer/projectm pull request #766
Opened 2024-02-02 04:47 UTC by dpw13

This PR adds a friend test for WaveformAligner that verifies a few internal implementation details as well as verifying proper alignment for waveforms with supported offsets.

This PR also refactors WaveformAligner for readability and fixes two bugs:
1) The code to calculate errorSum is supposed to calculate a windowed convolution but introduced an indexing bug that resulted in repeatedly calculating the product of the two waveforms instead.
2) The calculated "mip levels" or resampled waveforms were recalculated in the original Milkdrop code but was re-used as an optimization in the projectM code. However the re-used mip levels did not take the applied shift into account, resulting in the calculated offset being relative to the previous *unshifted* waveform. This bug was not present in the original Milkdrop code since the mip levels were recalculated including the applied shift.

2024-02-02 05:06 UTC, dpw13 commented on src/libprojectM/Audio/WaveformAligner.cpp
> +                errorSum += std::abs((newWaveformMips[octave][i + offset] - m_oldWaveformMips[octave][i]) * m_aligmentWeights[octave][i]);
Fix 1.

2024-02-02 05:07 UTC, dpw13 commented on src/libprojectM/Audio/WaveformAligner.cpp
> +    ResampleOctaves(m_oldWaveformMips, newWaveform);
Fix 2.

2024-02-02 14:12 UTC, kblaschke requested changes
Please split the individual changes into separate commits: one for the reformatting, one for each fix and one for the tests. This will make it easier to review and later much easier to see what was fixed where and why, without the need to dig up this PR.

If possible, add the reasoning for each change as mentioned in the PR into the respective commit messages.

2024-02-02 16:43 UTC, dpw13 commented
I split the commit into several pieces that should be much easier to review. I've explained what's changing in each commit. The commit that splits `Align` into multiple methods is likely the more difficult to review; I suggest disabling viewing whitespace changes with that commit. I've ordered the methods so hopefully the diff looks cleaner than before (where `ResampleOctaves` was placed too low in the file). The last commit contains only the actual fixes so `git blame` should make it clear what's changed and why.

2024-02-05 10:55 UTC, kblaschke approved these changes
Besides ideally running clang-format on the changed files before each commit, it looks good to me!

2024-02-05 10:55 UTC, kblaschke commented on src/libprojectM/Audio/WaveformAligner.cpp
> +int WaveformAligner::CalculateOffset(std::vector<WaveformBuffer> &newWaveformMips)
Better align reference/pointer designators to the type (or ideally use the .clang-format file in the root to format the code automatically).
`int WaveformAligner::CalculateOffset(std::vector<WaveformBuffer>& newWaveformMips)`

2024-02-05 10:55 UTC, kblaschke commented on src/libprojectM/Audio/WaveformAligner.hpp
> +    int CalculateOffset(std::vector<WaveformBuffer> &newWaveformMips);
Same here, just run clang-format, that should fix it.

2024-02-05 15:04 UTC, kblaschke approved these changes
Clean and well tested! If you're ready, I could merge at any time.

2024-02-05 15:19 UTC, Blaquewithaq approved these changes

2024-02-06 14:03 UTC, merged